import jsPDF from "jspdf";
import { NextRequest } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const data = await req.json();
    const { entityName, reportType, periodLabel, submittedAt, attestation, userName, recordCounts } = data;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = margin;

    // Header
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("Submission Receipt", pageWidth / 2, y, { align: "center" });
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("LCA Desk — Local Content Compliance Platform", pageWidth / 2, y, { align: "center" });
    y += 5;
    doc.text("https://app.lcadesk.com", pageWidth / 2, y, { align: "center" });
    y += 10;

    doc.setDrawColor(150);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    // Receipt ID
    const receiptId = `LCA-${Date.now().toString(36).toUpperCase()}`;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`Receipt ID: ${receiptId}`, margin, y);
    y += 10;

    // Submission details
    doc.setFontSize(12);
    doc.text("Submission Details", margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const details = [
      ["Company", entityName || "N/A"],
      ["Report Type", reportType || "N/A"],
      ["Reporting Period", periodLabel || "N/A"],
      ["Submitted At", submittedAt || new Date().toLocaleString()],
      ["Submitted By", userName || "N/A"],
    ];

    for (const [label, value] of details) {
      doc.text(`${label}:`, margin, y);
      doc.text(value, margin + 50, y);
      y += 6;
    }
    y += 5;

    // Record counts
    doc.setFont("helvetica", "bold");
    doc.text("Data Summary", margin, y);
    y += 8;
    doc.setFont("helvetica", "normal");

    const counts = [
      ["Expenditure Records", String(recordCounts?.expenditures || 0)],
      ["Employment Records", String(recordCounts?.employment || 0)],
      ["Capacity Development Records", String(recordCounts?.capacity || 0)],
    ];

    for (const [label, value] of counts) {
      doc.text(`${label}:`, margin, y);
      doc.text(value, margin + 65, y);
      y += 6;
    }
    y += 10;

    // Attestation
    doc.setDrawColor(150);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    doc.setFont("helvetica", "bold");
    doc.text("Attestation", margin, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    const attestLines = doc.splitTextToSize(
      attestation || "I certify that the information contained in this report is true and accurate.",
      pageWidth - margin * 2
    );
    doc.text(attestLines, margin, y);
    y += attestLines.length * 5 + 10;

    // Signature
    doc.text(`Attested by: ${userName || "N/A"}`, margin, y);
    y += 6;
    doc.text(`Date: ${submittedAt || new Date().toLocaleDateString()}`, margin, y);
    y += 15;

    // Regulatory note
    doc.setDrawColor(150);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Important:", margin, y);
    y += 5;
    doc.setFont("helvetica", "normal");
    const note = "This receipt confirms that a Local Content report was submitted through LCA Desk. The actual submission to the Local Content Secretariat must be made via email to localcontent@nre.gov.gy with the Excel report and PDF narrative attached. Retain this receipt for your compliance records.";
    const noteLines = doc.splitTextToSize(note, pageWidth - margin * 2);
    doc.text(noteLines, margin, y);

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(
      `Generated by LCA Desk — ${new Date().toISOString()} — Receipt ${receiptId}`,
      pageWidth / 2, 285, { align: "center" }
    );

    const buffer = doc.output("arraybuffer");

    return new Response(buffer as unknown as BodyInit, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="LCA_Desk_Submission_Receipt_${receiptId}.pdf"`,
      },
    });
  } catch (error) {
    console.error("Receipt PDF error:", error);
    return new Response("Failed to generate receipt", { status: 500 });
  }
}
