import jsPDF from "jspdf";
import type { ReportExportData } from "@/types/reporting.types";

export async function generateNarrativePdf(
  data: ReportExportData
): Promise<Uint8Array> {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  // Title
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Comparative Analysis Report", pageWidth / 2, y, { align: "center" });
  y += 10;

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text("Local Content Half-Yearly Submission", pageWidth / 2, y, { align: "center" });
  y += 15;

  // Company info
  doc.setFontSize(10);
  doc.text(`Company: ${data.entity.legal_name}`, margin, y);
  y += 6;
  doc.text(`LCS Certificate ID: ${data.entity.lcs_certificate_id || "N/A"}`, margin, y);
  y += 6;

  const periodLabel = data.period.report_type === "half_yearly_h1" ? "H1" : "H2";
  doc.text(
    `Reporting Period: ${periodLabel} ${data.period.fiscal_year} (${data.period.period_start} to ${data.period.period_end})`,
    margin,
    y
  );
  y += 6;
  doc.text(`Report Type: Half-Yearly Report`, margin, y);
  y += 12;

  // Divider
  doc.setDrawColor(150);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  // Expenditure Narrative
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Section A: Expenditure", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const expendLines = doc.splitTextToSize(data.narratives.expenditure || "No narrative provided.", contentWidth);
  doc.text(expendLines, margin, y);
  y += expendLines.length * 5 + 10;

  if (y > 250) {
    doc.addPage();
    y = margin;
  }

  // Employment Narrative
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Section B: Employment", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const employLines = doc.splitTextToSize(data.narratives.employment || "No narrative provided.", contentWidth);
  doc.text(employLines, margin, y);
  y += employLines.length * 5 + 10;

  if (y > 250) {
    doc.addPage();
    y = margin;
  }

  // Capacity Development Narrative
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Section C: Capacity Development", margin, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  const capLines = doc.splitTextToSize(data.narratives.capacity || "No narrative provided.", contentWidth);
  doc.text(capLines, margin, y);
  y += capLines.length * 5 + 15;

  if (y > 250) {
    doc.addPage();
    y = margin;
  }

  // Signature block
  doc.setDrawColor(150);
  doc.line(margin, y, pageWidth - margin, y);
  y += 10;

  doc.setFontSize(10);
  doc.text("Authorized Signatory: _________________________________", margin, y);
  y += 8;
  doc.text("Name: _________________________________", margin, y);
  y += 8;
  doc.text("Title: _________________________________", margin, y);
  y += 8;
  doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, y);

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by LCA Desk — Local Content Compliance Platform", pageWidth / 2, 285, {
    align: "center",
  });

  return doc.output("arraybuffer") as unknown as Uint8Array;
}
