// All 69 Related Sector values from the LCS Template v4.0
export const RELATED_SECTORS = [
  "Rental of Office Space",
  "Accommodation Services (Apartments & Houses)",
  "Equipment Rental",
  "Surveying",
  "Pipe Welding (Onshore)",
  "Pipe Sand Blasting and Coating (Onshore)",
  "Construction Work for Buildings (Onshore)",
  "Structural Fabrication",
  "Waste Management (Non-Hazardous)",
  "Waste Management (Hazardous)",
  "Storage Services",
  "Janitorial and Laundry Services",
  "Catering Services",
  "Food Supply",
  "Admin Support & Facilities Management Services",
  "Immigration Support Services",
  "Work Permit, Visas Applications, Visas on arrival and In-water Activity Permit",
  "Laydown Yard Facilities",
  "Customs Brokerage Services",
  "Export Packaging",
  "Pest Control Extermination Services",
  "Cargo Management/ Monitoring",
  "Ship & Rig Chandlery Services",
  "Borehole Testing Services",
  "Environment Services & Studies",
  "Transportation Services: Trucking",
  "Transportation Services: Ground Transportation",
  "Metrology Services",
  "Ventilation (private, commercial, industrial)",
  "Industrial Cleaning Services (Onshore)",
  "Security Services",
  "ICT-Network Installation, Support Services",
  "Manpower and Crewing Services",
  "Dredging Services",
  "Local Insurance Services",
  "Accounting Services",
  "Local Legal Services",
  "Medical Services",
  "Aviation Support Services",
  "Engineering and Machining",
  "Local Marketing & Advertising Services (PR)",
  "Other",
  "NDE and NDT",
  "Scaffolding and/or Rope Access Services",
  "Geographical Information and Data Services",
  "Offshore Paint",
  "Training",
  "CCU",
  "HSSE Supplies",
  "Offshore Pipe Coating and Insulation",
  "ROV Services",
  "Subsea Services",
  "MPSV services",
  "Freight Forwarding",
  "Inspection/Certification Services",
  "Marine Lubricants",
  "Commodity Chemicals",
  "Fuel Supply",
  "Industrial Supplies",
  "Lab Supplies",
  "Lab Testing Services",
  "Tank and/or Cleaning Services",
  "Valve Supplies",
  "Architectural and Engineering",
  "Project Management and Supervision",
  "ISO Consultancy and Certification Services.",
  "Supply Vessels",
  "Rigging",
  "Business and Management Consultancy",
];

export const PARTICIPANT_TYPES = [
  "Guyanese (Internal)",
  "Guyanese (External)",
  "Non-Guyanese (Internal)",
  "Non-Guyanese (External)",
  "Mixed (Internal)",
  "Mixed (External)",
  "Mixed",
  "Guyanese Supplier",
  "Non-Guyanese Supplier",
  "Mixed Supplier",
];
