import jsPDF from "jspdf";
import { NextRequest } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const data = await req.json();
    const { posting, applications, compliance } = data;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = margin;

    // Title
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("First Consideration Record", pageWidth / 2, y, { align: "center" });
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text("Local Content Act 2021 — Section 12 Compliance", pageWidth / 2, y, { align: "center" });
    y += 12;

    doc.setDrawColor(150);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    // Position details
    doc.setFontSize(12);
    doc.setFont("helvetica", "bold");
    doc.text("Position Details", margin, y);
    y += 8;

    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    const details = [
      ["Job Title", posting.jobTitle],
      ["Employment Category", posting.employmentCategory],
      ["Contract Type", posting.contractType],
      ["Location", posting.location || "Not specified"],
      ["Vacancies", String(posting.vacancyCount)],
      ["Posted Date", posting.postedDate ? new Date(posting.postedDate).toLocaleDateString() : "N/A"],
      ["Application Deadline", posting.deadline || "Open"],
    ];

    for (const [label, value] of details) {
      doc.text(`${label}:`, margin, y);
      doc.text(value, margin + 55, y);
      y += 6;
    }
    y += 5;

    // First consideration statement
    doc.setFont("helvetica", "bold");
    doc.text("First Consideration Statement", margin, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    const statement = posting.guyaneseFirstStatement || compliance.statement || "";
    const statementLines = doc.splitTextToSize(statement, pageWidth - margin * 2);
    doc.text(statementLines, margin, y);
    y += statementLines.length * 5 + 10;

    // Application summary
    doc.setFont("helvetica", "bold");
    doc.text("Application Summary", margin, y);
    y += 8;
    doc.setFont("helvetica", "normal");

    const appDetails = [
      ["Total Applications Received", String(applications.total)],
      ["Guyanese Applicants", String(applications.guyanese)],
      ["Non-Guyanese Applicants", String(applications.nonGuyanese)],
      ["Applicants Selected", String(applications.selected)],
      ["Guyanese Selected", String(applications.guyaneseSelected)],
    ];

    for (const [label, value] of appDetails) {
      doc.text(`${label}:`, margin, y);
      doc.text(value, margin + 60, y);
      y += 6;
    }
    y += 10;

    // Compliance declaration
    doc.setDrawColor(150);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    doc.setFont("helvetica", "bold");
    doc.text("Declaration", margin, y);
    y += 8;
    doc.setFont("helvetica", "normal");
    const declaration = `This document confirms that first consideration was given to qualified Guyanese nationals for the above position(s) in accordance with Section 12 of the Local Content Act No. 18 of 2021.`;
    const declLines = doc.splitTextToSize(declaration, pageWidth - margin * 2);
    doc.text(declLines, margin, y);
    y += declLines.length * 5 + 15;

    // Signature block
    doc.text("Authorized Signatory: _________________________________", margin, y);
    y += 8;
    doc.text("Name: _________________________________", margin, y);
    y += 8;
    doc.text("Title: _________________________________", margin, y);
    y += 8;
    doc.text(`Date: ${new Date().toLocaleDateString()}`, margin, y);

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(150);
    doc.text(
      `Generated by LCA Desk — ${compliance.generatedAt || new Date().toISOString()}`,
      pageWidth / 2,
      285,
      { align: "center" }
    );

    const buffer = doc.output("arraybuffer");

    return new Response(buffer as unknown as BodyInit, {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="First_Consideration_Record_${posting.jobTitle.replace(/\s+/g, "_")}.pdf"`,
      },
    });
  } catch (error) {
    console.error("First consideration PDF error:", error);
    return new Response("Failed to generate PDF", { status: 500 });
  }
}
